SCA:
    adc:
    gpio:
        mod_d01:
            pin: 0x1F
            default: 0
            direction: out
            flavor: small
            comment: pin 30 in ETROC 0 and 1
        mod_d09:
            pin: 0x19
            default: 0
            direction: out
            flavor: small
            comment: pin 30 in ETROC 4 and 5
        mod_d17:
            pin: 0x0E
            default: 0
            direction: out
            flavor: small
            comment: pin 30 in ETROC 8 and 9

LPGBT:
    adc:
    gpio:

inversions:
    clocks:
      - 3
      - 4
      - 5
      - 22
      - 23
      - 25
      - 26
      - 27
    downlink:
      - 2
      - 4
      - 8
      - 10
      - 12
    uplink:
      - 6
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
    trigger:
      - 2
      - 6
      - 10
      - 16
      - 18
      - 20
      - 22
modules:
  1:
   elinks: [[[0],[0]], [[2],[2]], [[20],[20]], [[22],[22]]]
   addresses: [0x72, 0x72, 0x72, 0x72]
   i2c:
     master: lpgbt
     channel: 1
   status: mod_d01
  2:
   elinks: [[[4],[4]], [[6],[6]], [[16],[16]], [[18],[18]]]
   addresses: [0x72, 0x72, 0x72, 0x72]
   i2c:
     master: sca
     channel: 3
   status: mod_d09
  3:
    elinks: [[[8],[8]], [[10],[10]], [[12],[12]], [[14],[14]]]
    addresses: [0x72, 0x72, 0x72, 0x72]
    i2c:
      master: sca
      channel: 0
    status: mod_d17
