emulator_adapter:
   clocks:
      - 3
      - 4
      - 5
      - 22
      - 23
      - 25
      - 26
      - 27
   downlink:
      - 2     
      - 4    
      - 8    
      - 10   
      - 12 
   uplink:
      - 6
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
   trigger:
      - 2
      - 6
      - 10
      - 16
      - 18
      - 20
      - 22
