adc:
    TH1:
        pin: 0x00
        conv: 1
        min: 0
        max: 1.0
        flavor: small
        comment: VTRX TH1
    1V4D_ADC:
        pin: 0x01
        conv: 1.82
        min: 1.12
        max: 1.68
        flavor: small
        comment: 1V4D * 0.55
    1V5A_ADC:
        pin: 0x02
        conv: 1.82
        min: 1.2
        max: 1.8
        flavor: small
        comment: 1V5D * 0.55
    2V5TX_ADC:
        pin: 0x03
        conv: 3.0
        min: 2.0
        max: 3.0
        flavor: small
        comment: 2V5TX * 0.33
    RSSI_ADC:
        pin: 0x04
        conv: 1
        min: 0
        max: 1.0
        flavor: small
        comment: RSSI
    ADC5:
        pin: 0x05
        conv: 1
        min: 0
        max: 1.0
        flavor: small
        comment: N/A
    2V5RX_ADC:
        pin: 0x06
        conv: 3.0
        min: 2.0
        max: 3.0
        flavor: small
        comment: 2V5RX * 0.33
    VTEMP_ADC:
        pin: 0x07
        conv: 1
        min: 0
        max: 1.0
        flavor: small
        comment: RT1
    EOM_ADC:
        pin: 0x08
        conv: 1
        flavor: small
        comment: EOM DAC (internal signal)
    VDDIO:
        pin: 0x09
        conv: 2.38
        flavor: small
        comment: VDDIO * 0.42 (internal signal)
    VDDTX:
        pin: 0x0a
        conv: 2.38
        flavor: small
        comment: VDDTX * 0.42 (internal signal)
    VDDRX:
        pin: 0x0b
        conv: 2.38
        flavor: small
        comment: VDDRX * 0.42 (internal signal)
    VDD:
        pin: 0x0c
        conv: 2.38
        flavor: small
        comment: VDD * 0.42 (internal signal)
    VDDA:
        pin: 0x0d
        conv: 2.38
        flavor: small
        comment: VDDA * 0.42 (internal signal)
    TEMP:
        pin: 0x0e
        conv: 1
        flavor: small
        comment: Temperature sensor (internal signal)
    VREF:
        pin: 0x0f
        conv: 2.0
        flavor: small
        comment: VREF/2 (internal signal)
gpio:
    SCA_RESETB:
        pin: 0x00
        default: 1
        direction: out
        flavor: small
        comment: GBT SCA reset
    LED_0:
        pin: 0x01
        default: 0
        direction: in
        flavor: small
        comment: LPGBT GPIO configuration LED
    LED_1:
        pin: 0x02
        default: 0
        direction: in
        flavor: small
        comment: tamalero LED
    LED_RHETT:
        pin: 0x03
        default: 1
        direction: out
        flavor: small
        comment: success LED
    LD_RSTN:
        pin: 0x0A
        default: 1
        direction: out
        flavor: small
        comment: VTRX reset
    LD_DIS:
        pin: 0x0D
        default: 0
        direction: out
        flavor: small
        comment: VTRX DIS
